export const styles = {
  h3a: {
    fontStyle: "normal",
    marginTop: "0.75cm",
    position: "absolute",
    marginLeft: "1.5cm",
  },
  h4a: {
    marginTop: "0.4cm",
    position: "absolute",
    marginLeft: "34cm",
    top: "0",
  },
  array_contain: {
    marginTop: "1.7cm",
    marginLeft: "0.1cm",
    position: "absolute",
    left: "10px",
    width: "100%",
    backgroundColor: "black",
  },
  button: {
    fontWeight: "bold",
    marginTop: "0.4cm",
    marginLeft: "13cm",
    cursor: "pointer",
    boxShadow: "0px 8px 15px rgba(71, 142, 255, 0.1)",
    position: "absolute",
  },
  button1: {
    fontWeight: "bold",
    marginLeft: "16cm",
    marginTop: "0.4cm",
    cursor: "pointer",
    boxShadow: "0px 8px 15px rgba(71, 142, 255, 0.1)",
    position: "absolute",
  },
  button2: {
    fontWeight: "bold",
    marginLeft: "19cm",
    marginTop: "0.4cm",
    cursor: "pointer",
    boxShadow: "0px 8px 15px rgba(71, 142, 255, 0.1)",
    position: "absolute",
  },
  button3: {
    fontWeight: "bold",
    marginLeft: "22cm",
    marginTop: "0.4cm",
    cursor: "pointer",
    boxShadow: "0px 8px 15px rgba(71, 142, 255, 0.1)",
    position: "absolute",
  },
  button4: {
    fontWeight: "bold",
    marginLeft: "25cm",
    marginTop: "0.4cm",
    cursor: "pointer",
    boxShadow: "0px 8px 15px rgba(71, 142, 255, 0.1)",
    position: "absolute",
  },
  button5: {
    fontWeight: "bold",
    marginLeft: "28cm",
    marginTop: "0.4cm",
    cursor: "pointer",
    boxShadow: "0px 8px 15px rgba(71, 142, 255, 0.1)",
    position: "absolute",
  },
  button6: {
    fontWeight: "bold",
    marginLeft: "31cm",
    marginTop: "0.4cm",
    boxShadow: "0px 8px 15px rgba(71, 142, 255, 0.1)",
    position: "absolute",
  },
  array_bar: {
    width: "2.25px",
    backgroundColor: "turquoise",
    display: "inline-block",
    margin: "0.8px",
  },
  navBar: {
    display: "inline",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 100,
    color: "aliceblue",
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    fontStyle: "oblique",
    backgroundColor: "navy",
    height: "2cm",
    width: "40cm",
    marginLeft: "0.1cm",
  },
  bardiv: {
    marginTop: "1cm",
    height: "17cm",
    marginLeft: "0.1cm",
    marginRight: "1cm",
    position: "absolute",
    display: "block",
  },

  div1: {
    position: "absolute",
    backgroundColor: "white",
    marginLeft: "1cm",
    width: "17cm",
    height: "12cm",
    borderRadius: "45px",
  },
  nav1: {
    marginLeft: "0.3cm",
    backgroundColor: "blue",
    width: "16.2cm",
    height: "1cm",
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    color: "white",
    top: "0cm",
  },
  textarea1: {
    fontSize: "16px",
    resize: "none",
    width: "16cm",
    height: "10cm",
    color: "white",
    borderColor: "black",
    backgroundColor: "black",
    marginLeft: "0.3cm",
  },
  forceStop: {
    marginLeft: "11cm",
    position: "absolute",
    marginTop: "0.2cm",
    boxShadow: "2px 2px black",
    cursor: "pointer",
    width: "4cm",
    height: "1cm",
    backgroundColor: "red",
    color: "white",
  },
  range: {
    top: "0",
    marginLeft: "34cm",
    position: "absolute",
    marginTop: "1cm",
    // overflow:'auto'
  },
};
